
- name: Install required system packages
  apt:
    name:
      - apt-transport-https
      - ca-certificates
      - curl
      - gnupg
      - lsb-release
    state: latest
    update_cache: yes
  tags:
    - install_docker


- name: Add Docker GPG apt Key
  apt_key:
    url: "https://download.docker.com/linux/{{ ansible_distribution | lower }}/gpg"
    state: present
  tags:
    - install_docker


- name: Add Docker Repository
  apt_repository:
    repo: "deb https://download.docker.com/linux/{{ ansible_distribution | lower }} {{ ansible_distribution_release }} stable"
    state: present
  tags:
    - install_docker


- name: Install docker
  apt:
    update_cache: true
    name: "{{ item }}"
    state: present
  loop:
    - docker-ce 
    - docker-ce-cli
    - containerd.io
  tags:
    - install_docker


- name: Install docker-compose
  get_url:
    url: https://github.com/docker/compose/releases/download/1.29.2/docker-compose-Linux-x86_64
    dest: /usr/local/bin/docker-compose
    mode: '0755'
  tags:
    -install_docker_compose

